"""Deterministic, multilingual decision-letter rendering.

The letter is generated by templating (never by an LLM) from the frozen fields of a
``DecisionLetter`` row: applicant ID, decision date, outcome, the same reason codes the
model produced, the model version, and (once signed) the officer's identity. Because the
reasons come straight from the glass-box model's own reason codes, the letter cannot
disagree with the decision it explains.

Rendering is server-side so the letter is a self-contained, reproducible document in the
borrower's chosen language (English / Hindi / Bengali), not something reassembled by the
frontend. Reason phrases drawn from the model's fixed vocabulary are translated; any
dynamically-composed qualifier (thin-file, consent-withdrawal, panel disagreement) falls
back to its stored English text.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from core.date_i18n import format_human_date

SUPPORTED_LANGUAGES = ("en", "hi", "bn")

# Letter scaffold: every field label + boilerplate, per language.
LETTER_I18N: dict[str, dict[str, str]] = {
    "en": {
        "title_reject": "Notice of credit decision",
        "title_review": "Notice: application under review",
        "title_approve": "Notice of credit approval",
        "subtitle": "Issued under the fair-lending disclosure requirement",
        "ref_label": "Reference",
        "date_label": "Decision date",
        "applicant_label": "Applicant ID",
        "outcome_label": "Decision",
        "model_label": "Model version",
        "outcome_reject": "Application declined",
        "outcome_review": "Referred for manual review",
        "outcome_approve": "Application approved",
        "body_reject": "After assessing your application using alternative data, we are unable to approve the credit facility at this time. The principal reasons are set out below.",
        "body_review": "Your application requires additional review by a loan officer before a final decision can be issued. The main factors under consideration are set out below.",
        "body_approve": "We are pleased to inform you that your application has been approved. This notice records the basis of that decision.",
        "reasons_heading": "Principal reasons for this decision",
        "no_reasons": "No specific adverse factors were recorded.",
        "rights": "Under Reserve Bank of India guidelines you have the right to know why this decision was made, and to request a review. Your assessment used alternative data such as telecom and utility payment records.",
        "grievance": "To question or appeal this decision, contact the Nodal Grievance Officer. If your complaint is not resolved within 30 days, you may escalate it to the RBI Ombudsman at https://cms.rbi.org.in.",
        "signed_by": "Reviewed and signed by",
        "signed_on": "Signed on",
        "auto_note": "Issued automatically on approval; no manual review was required.",
        "pending_note": "This is a preliminary result. A loan officer will review and sign the formal notice, which will then appear in your account.",
        "officer_pending": "Awaiting officer review",
    },
    "hi": {
        "title_reject": "ऋण निर्णय की सूचना",
        "title_review": "सूचना: आवेदन समीक्षाधीन",
        "title_approve": "ऋण स्वीकृति की सूचना",
        "subtitle": "निष्पक्ष ऋण प्रकटीकरण आवश्यकता के अंतर्गत जारी",
        "ref_label": "संदर्भ",
        "date_label": "निर्णय तिथि",
        "applicant_label": "आवेदक आईडी",
        "outcome_label": "निर्णय",
        "model_label": "मॉडल संस्करण",
        "outcome_reject": "आवेदन अस्वीकृत",
        "outcome_review": "मैनुअल समीक्षा हेतु भेजा गया",
        "outcome_approve": "आवेदन स्वीकृत",
        "body_reject": "वैकल्पिक डेटा का उपयोग करके आपके आवेदन का मूल्यांकन करने के बाद, हम इस समय ऋण सुविधा को स्वीकृत करने में असमर्थ हैं। मुख्य कारण नीचे दिए गए हैं।",
        "body_review": "अंतिम निर्णय जारी करने से पहले आपके आवेदन की एक ऋण अधिकारी द्वारा अतिरिक्त समीक्षा आवश्यक है। विचाराधीन मुख्य कारक नीचे दिए गए हैं।",
        "body_approve": "हमें आपको यह सूचित करते हुए प्रसन्नता है कि आपका आवेदन स्वीकृत कर लिया गया है। यह सूचना उस निर्णय का आधार दर्ज करती है।",
        "reasons_heading": "इस निर्णय के मुख्य कारण",
        "no_reasons": "कोई विशिष्ट प्रतिकूल कारक दर्ज नहीं किया गया।",
        "rights": "भारतीय रिज़र्व बैंक के दिशानिर्देशों के तहत, आपको यह जानने का अधिकार है कि यह निर्णय क्यों लिया गया, और समीक्षा का अनुरोध करने का अधिकार है। आपके मूल्यांकन में टेलीकॉम और उपयोगिता भुगतान रिकॉर्ड जैसे वैकल्पिक डेटा का उपयोग किया गया।",
        "grievance": "इस निर्णय पर प्रश्न या अपील के लिए, नोडल शिकायत अधिकारी से संपर्क करें। यदि आपकी शिकायत 30 दिनों के भीतर हल नहीं होती है, तो आप इसे आरबीआई लोकपाल के पास https://cms.rbi.org.in पर बढ़ा सकते हैं।",
        "signed_by": "समीक्षा और हस्ताक्षर द्वारा",
        "signed_on": "हस्ताक्षर तिथि",
        "auto_note": "स्वीकृति पर स्वतः जारी; किसी मैनुअल समीक्षा की आवश्यकता नहीं थी।",
        "pending_note": "यह एक प्रारंभिक परिणाम है। एक ऋण अधिकारी औपचारिक सूचना की समीक्षा कर हस्ताक्षर करेंगे, जो फिर आपके खाते में दिखाई देगी।",
        "officer_pending": "अधिकारी समीक्षा प्रतीक्षित",
    },
    "bn": {
        "title_reject": "ঋণ সিদ্ধান্তের বিজ্ঞপ্তি",
        "title_review": "বিজ্ঞপ্তি: আবেদন পর্যালোচনাধীন",
        "title_approve": "ঋণ অনুমোদনের বিজ্ঞপ্তি",
        "subtitle": "ন্যায্য-ঋণ প্রকাশ প্রয়োজনীয়তার অধীনে জারি",
        "ref_label": "রেফারেন্স",
        "date_label": "সিদ্ধান্তের তারিখ",
        "applicant_label": "আবেদনকারী আইডি",
        "outcome_label": "সিদ্ধান্ত",
        "model_label": "মডেল সংস্করণ",
        "outcome_reject": "আবেদন প্রত্যাখ্যাত",
        "outcome_review": "ম্যানুয়াল পর্যালোচনার জন্য পাঠানো হয়েছে",
        "outcome_approve": "আবেদন অনুমোদিত",
        "body_reject": "বিকল্প তথ্য ব্যবহার করে আপনার আবেদন মূল্যায়নের পর, আমরা এই মুহূর্তে ঋণ সুবিধা অনুমোদন করতে অক্ষম। প্রধান কারণগুলি নীচে দেওয়া হল।",
        "body_review": "চূড়ান্ত সিদ্ধান্ত জারির আগে আপনার আবেদনটি একজন ঋণ কর্মকর্তার দ্বারা অতিরিক্ত পর্যালোচনা প্রয়োজন। বিবেচনাধীন প্রধান বিষয়গুলি নীচে দেওয়া হল।",
        "body_approve": "আপনাকে জানাতে পেরে আনন্দিত যে আপনার আবেদন অনুমোদিত হয়েছে। এই বিজ্ঞপ্তি সেই সিদ্ধান্তের ভিত্তি নথিভুক্ত করে।",
        "reasons_heading": "এই সিদ্ধান্তের প্রধান কারণ",
        "no_reasons": "কোনও নির্দিষ্ট প্রতিকূল কারণ নথিভুক্ত করা হয়নি।",
        "rights": "ভারতীয় রিজার্ভ ব্যাঙ্কের নির্দেশিকা অনুযায়ী, এই সিদ্ধান্ত কেন নেওয়া হয়েছে তা জানার এবং পর্যালোচনার অনুরোধ করার অধিকার আপনার আছে। আপনার মূল্যায়নে টেলিকম ও ইউটিলিটি পেমেন্ট রেকর্ডের মতো বিকল্প তথ্য ব্যবহার করা হয়েছে।",
        "grievance": "এই সিদ্ধান্ত নিয়ে প্রশ্ন বা আপিলের জন্য নোডাল অভিযোগ কর্মকর্তার সাথে যোগাযোগ করুন। ৩০ দিনের মধ্যে সমাধান না হলে, আপনি আরবিআই ওম্বুডসম্যানের কাছে https://cms.rbi.org.in-এ অভিযোগ জানাতে পারেন।",
        "signed_by": "পর্যালোচনা ও স্বাক্ষর করেছেন",
        "signed_on": "স্বাক্ষরের তারিখ",
        "auto_note": "অনুমোদনে স্বয়ংক্রিয়ভাবে জারি; কোনও ম্যানুয়াল পর্যালোচনার প্রয়োজন হয়নি।",
        "pending_note": "এটি একটি প্রাথমিক ফলাফল। একজন ঋণ কর্মকর্তা আনুষ্ঠানিক বিজ্ঞপ্তি পর্যালোচনা ও স্বাক্ষর করবেন, যা তখন আপনার অ্যাকাউন্টে প্রদর্শিত হবে।",
        "officer_pending": "কর্মকর্তার পর্যালোচনার অপেক্ষায়",
    },
}

# Translations for the model's fixed reason vocabulary. Keyed on the English label
# stored in the letter (see convergence.reason_codes.FEATURE_REASON_MAP).
REASON_I18N: dict[str, dict[str, str]] = {
    "Irregular bill payment timing": {"hi": "अनियमित बिल भुगतान समय", "bn": "অনিয়মিত বিল পরিশোধের সময়"},
    "Missed telecom or utility payments": {"hi": "छूटे हुए टेलीकॉम या उपयोगिता भुगतान", "bn": "টেলিকম বা ইউটিলিটি পেমেন্ট বাদ পড়া"},
    "Low share of essential spending": {"hi": "आवश्यक खर्च का कम अनुपात", "bn": "প্রয়োজনীয় ব্যয়ের কম অংশ"},
    "Low merchant quality in purchase history": {"hi": "खरीद इतिहास में कम विक्रेता गुणवत्ता", "bn": "ক্রয় ইতিহাসে কম মার্চেন্ট মান"},
    "High spending volatility": {"hi": "उच्च खर्च अस्थिरता", "bn": "উচ্চ ব্যয় অস্থিরতা"},
    "Geographic instability": {"hi": "भौगोलिक अस्थिरता", "bn": "ভৌগোলিক অস্থিরতা"},
    "Limited location anchors": {"hi": "सीमित स्थान संदर्भ", "bn": "সীমিত অবস্থান নোঙর"},
    "Low or unstable income": {"hi": "कम या अस्थिर आय", "bn": "কম বা অস্থিতিশীল আয়"},
    "High recurring expenses": {"hi": "उच्च आवर्ती व्यय", "bn": "উচ্চ পুনরাবৃত্ত ব্যয়"},
    "Volatile cash flow patterns": {"hi": "अस्थिर नकदी प्रवाह पैटर्न", "bn": "অস্থির নগদ প্রবাহ প্যাটার্ন"},
    "Signs of less careful financial planning": {"hi": "कम सावधान वित्तीय योजना के संकेत", "bn": "কম সতর্ক আর্থিক পরিকল্পনার লক্ষণ"},
    "Feels finances are outside their control": {"hi": "वित्त को अपने नियंत्रण से बाहर महसूस करना", "bn": "অর্থ নিজের নিয়ন্ত্রণের বাইরে বলে মনে করা"},
    "Low confidence managing personal finances": {"hi": "व्यक्तिगत वित्त प्रबंधन में कम आत्मविश्वास", "bn": "ব্যক্তিগত অর্থ পরিচালনায় কম আত্মবিশ্বাস"},
    "Tends to spend impulsively rather than save": {"hi": "बचत के बजाय आवेगपूर्ण खर्च की प्रवृत्ति", "bn": "সঞ্চয়ের বদলে আবেগপ্রবণ খরচের প্রবণতা"},
    "Weak commitment to timely debt repayment": {"hi": "समय पर ऋण चुकौती के प्रति कमजोर प्रतिबद्धता", "bn": "সময়মতো ঋণ পরিশোধে দুর্বল প্রতিশ্রুতি"},
    "Inconsistent answers in the assessment": {"hi": "मूल्यांकन में असंगत उत्तर", "bn": "মূল্যায়নে অসামঞ্জস্যপূর্ণ উত্তর"},
    "Low financial resilience": {"hi": "कम वित्तीय लचीलापन", "bn": "কম আর্থিক সহনশীলতা"},
    "Non-stationary income/expense pattern": {"hi": "अस्थिर आय/व्यय पैटर्न", "bn": "অস্থিতিশীল আয়/ব্যয় প্যাটার্ন"},
    "Unstable long-run cash flow equilibrium": {"hi": "अस्थिर दीर्घकालिक नकदी प्रवाह संतुलन", "bn": "অস্থিতিশীল দীর্ঘমেয়াদী নগদ প্রবাহ ভারসাম্য"},
    "Declining income trend": {"hi": "घटती आय प्रवृत्ति", "bn": "হ্রাসমান আয়ের প্রবণতা"},
    "Inconsistent delivery locations": {"hi": "असंगत डिलीवरी स्थान", "bn": "অসামঞ্জস্যপূর্ণ ডেলিভারি অবস্থান"},
    "Multiple delivery addresses": {"hi": "एकाधिक डिलीवरी पते", "bn": "একাধিক ডেলিভারি ঠিকানা"},
}


def _normalise_lang(lang: str | None) -> str:
    return lang if lang in SUPPORTED_LANGUAGES else "en"


def _translate_reason(label: str, lang: str) -> str:
    if lang == "en":
        return label
    return REASON_I18N.get(label, {}).get(lang, label)


def _outcome_kind(outcome: str) -> str:
    """Map any decision string onto one of approve / review / reject."""
    value = (outcome or "").upper()
    if value == "APPROVE":
        return "approve"
    if value == "REJECT":
        return "reject"
    return "review"


def render_letter(letter: dict[str, Any], lang: str | None = "en") -> dict[str, Any]:
    """Render a frozen letter record into a structured, translated document.

    ``letter`` carries the persisted fields: ``user_id``, ``status``, ``outcome``,
    ``credit_score``, ``model_version``, ``reason_codes`` (list of English labels),
    ``created_at``, and optionally ``officer_id`` / ``signed_at``.
    """
    lang = _normalise_lang(lang)
    strings = LETTER_I18N[lang]
    kind = _outcome_kind(letter.get("outcome", "REVIEW"))

    reasons = [_translate_reason(r, lang) for r in (letter.get("reason_codes") or [])]

    created = letter.get("created_at")
    date_str = format_human_date(created.date(), lang) if isinstance(created, datetime) else str(created or "")
    signed = letter.get("signed_at")
    signed_str = format_human_date(signed.date(), lang) if isinstance(signed, datetime) else (str(signed) if signed else None)

    user_id = str(letter.get("user_id", ""))
    ref = "AC-" + datetime.now(timezone.utc).strftime("%Y") + "-" + user_id.replace("-", "")[:8].upper()

    body = {
        "title": strings[f"title_{kind}"],
        "subtitle": strings["subtitle"],
        "ref_label": strings["ref_label"],
        "ref": ref,
        "date_label": strings["date_label"],
        "date": date_str,
        "applicant_label": strings["applicant_label"],
        "applicant_id": (user_id[:8] + "··· (masked)") if user_id else "—",
        "outcome_label": strings["outcome_label"],
        "outcome_text": strings[f"outcome_{kind}"],
        "model_label": strings["model_label"],
        "model_version": str(letter.get("model_version", "")),
        "body_text": strings[f"body_{kind}"],
        "reasons_heading": strings["reasons_heading"],
        "reasons": reasons or [strings["no_reasons"]],
        "rights": strings["rights"],
        "grievance": strings["grievance"],
        "signed_by_label": strings["signed_by"],
        "signed_on_label": strings["signed_on"],
    }

    status = letter.get("status", "pending_review")
    if status == "pending_review":
        body["status_note"] = strings["pending_note"]
        body["officer"] = strings["officer_pending"]
    elif letter.get("officer_id"):
        body["officer"] = letter["officer_id"]
        body["signed_on"] = signed_str
    else:
        body["status_note"] = strings["auto_note"]

    return {
        "user_id": user_id,
        "status": status,
        "outcome": letter.get("outcome"),
        "language": lang,
        "letter": body,
        "plain_text": _to_plain_text(body, status),
    }


def _to_plain_text(body: dict[str, Any], status: str) -> str:
    """A downloadable plain-text rendering of the letter."""
    lines = [
        body["title"].upper(),
        body["subtitle"],
        "",
        f"{body['ref_label']}: {body['ref']}",
        f"{body['date_label']}: {body['date']}",
        f"{body['applicant_label']}: {body['applicant_id']}",
        f"{body['outcome_label']}: {body['outcome_text']}",
        f"{body['model_label']}: {body['model_version']}",
        "",
        body["body_text"],
        "",
        body["reasons_heading"] + ":",
    ]
    lines += [f"  {i}. {r}" for i, r in enumerate(body["reasons"], start=1)]
    lines += ["", body["rights"], "", body["grievance"], ""]
    if body.get("officer") and status == "issued" and body.get("signed_on"):
        lines.append(f"{body['signed_by_label']}: {body['officer']} ({body['signed_on_label']}: {body['signed_on']})")
    elif body.get("status_note"):
        lines.append(body["status_note"])
    return "\n".join(lines)
